### ISSUE TITLE
Update `nodes.js` to version 16

### ISSUE THREAD

**Issue by radiomix** [JoshuaTheMiller/matrixfilter-action#3]
In `action.yml` https://github.com/JoshuaTheMiller/conditional-build-matrix/blob/b9af2b1b137d7bd7818c1233ef830b326809a7cc/action.yml#L20 you reference an old version of `node`. This results in a warning running Github Actions.
>:warning:  Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: JoshuaTheMiller/conditional-build-matrix

Could you please update the node version?

**Comment by JoshuaTheMiller** [comment]
Updating to [`v1.0.0`](https://github.com/JoshuaTheMiller/conditional-build-matrix-test/commit/5b25eef8dd9b43449542a6745bb25c5ac1332b4f) will fix the warning. Thanks for the Issue ☺
